export const cities = [
  'Madrid',
  'Barcelona',
  'Valencia',
  'Sevilla',
  'Zaragoza',
  'Málaga',
  'Murcia',
  'Palma de Mallorca',
  'Las Palmas de Gran Canaria',
  'Bilbao',
  'Alicante',
  'Córdoba',
  'Valladolid',
  'Vigo',
  'Gijón',
  "L'Hospitalet de Llobregat",
  'La Coruña',
  'Granada',
  'Elche',
  'Oviedo',
  'Badalona',
  'Cartagena',
  'Terrassa',
  'Jerez de la Frontera',
  'Sabadell',
  'Santa Cruz de Tenerife',
  'Almería',
  'Getafe',
  'Cádiz',
  'Mataró',
  'Leganés',
  'Burgos',
  'Santander',
  'Alcalá de Henares',
  'Fuenlabrada',
  'Castellón de la Plana',
  'Albacete',
  'San Sebastián',
  'Tarragona',
  'Badajoz',
  'Lleida',
  'Marbella',
  'Huelva',
  'Pontevedra'
];
